-- Basic Aggregate Functions:
## Question 1: Retrieve the total number of rentals made in the Sakila database.
use sakila;
select count(distinct rental_id) as total_rental from rental;

## Question 2: Find the average rental duration (in days) of movies rented from the Sakila database.
SELECT * FROM film;
SELECT round(avg(rental_duration),0) as Avg_rental_dur_days from film;
-- OR
SELECT ROUND(AVG(DATEDIFF(return_date, rental_date)), 0) AS Avg_rental_dur_days
FROM rental
WHERE return_date IS NOT NULL;
-- -----------------------------------------

# String Functions:
## Question 3: Display the first name and last name of customers in uppercase.
select UPPER(first_name), UPPER(last_name) from customer;

## Question 4: Extract the month from the rental date and display it alongside the rental ID.
select * from rental;
select rental_id, MONTH(rental_date) as rental_month, MONTHNAME(rental_date) as rental_month_name from rental;
-- ------------------------------
## GROUP BY:
## Question 5: Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select customer_id, count(*) as total_rental from rental
group by customer_id;

## Question 6: Find the total revenue generated by each store.
select * from payment;
select * from staff;
select * from store;

select st.store_id, sum(p.amount) as total_revenue from payment p
inner join staff st
on st.staff_id = p.staff_id
inner join store s 
on s.store_id = st.store_id
group by s.store_id;

## Question 7: Determine the total number of rentals for each category of movies.
select * from rental;
select * from inventory;
select * from film_category;
select * from film;
select * from category;

select c.name, count(r.rental_id) as total_rentals from rental r
inner join inventory i 
on r.inventory_id = i.inventory_id
inner join film f 
on i.film_id = f.film_id
inner join film_category fc
on  f.film_id = fc.film_id
inner join category c
on fc.category_id = c.category_id
group by c.name;

## Question 8: Find the average rental rate of movies in each language.
select * from language;
select avg(f.rental_rate) as avg_rental_rate, l.name from film f
join language l on f.language_id = l.language_id
group by l.name;
